<h1 id="프로그램-오류에러--error">프로그램 오류(에러  Error)</h1>
<ul>
<li>발생 시점에 따른 구분</li>
</ul>
<table>
<thead>
<tr>
<th>에러</th>
<th>내용</th>
</tr>
</thead>
<tbody><tr>
<td>컴파일 에러</td>
<td>컴파일 도중 컴파일러가 발견하는 오류</td>
</tr>
<tr>
<td>런타임 에러</td>
<td>컴파일은 성공적으로 진행 되었으나, 프로그램 실행 중에 발생하는 오류</td>
</tr>
<tr>
<td>논리적 에러</td>
<td>컴파일도 되고 프로그램도 실행 되었으나, 프로그램이 의도대로 동작하지 않는 오류, 프로그램이 정상적으로 실행되고 종료되었지만 결과가 예상과 다른 경우</td>
</tr>
<tr>
<td>- 에러와 예외</td>
<td></td>
</tr>
<tr>
<td>- 에러Error : 발생하면 복수할 수 없는 심각한 오류 ( 메모리 부족, 스택 오버 플로우 )</td>
<td></td>
</tr>
<tr>
<td>- 예외Exception : 프로그래머가 적절한 코드를 통해 대비할 수 있는 오류 ( 클래스 형 변환 실패, 파일 읽기 실패 )</td>
<td></td>
</tr>
</tbody></table>
<h3 id="예외처리란-">예외처리란 ?</h3>
<p>예외 발생 시 프로그램의 비 정상 종료를 막고 정상적인 실행 상태를 유지하는 것</p>
<p>예외의 감지 및 예외 발생 시 동작할 코드 작성하고, 사용자에게 적절한 메시지 제공</p>
<ul>
<li><p>예외도 하나의 객체이다.</p>
<blockquote>
<p>Checked : Exception 계열, 예외에 대한 대처 코드가 없으면 컴파일이 진행되지 않음</p>
</blockquote>
<blockquote>
<p>UnChecked : RunTimeException 계열, 예외에 대한 대처 코드가 없어도 컴파일 진행</p>
</blockquote>
</li>
</ul>
<h2 id="예외의-계열">예외의 계열</h2>
<ul>
<li>RuntimeException 클래스들<ul>
<li>프로그래머의 실수로 발생</li>
<li>unchecked exception</li>
<li>대처코드가 없어도 컴파일 문제 X</li>
</ul>
</li>
<li>Exception 클래스들<ul>
<li>사용자의 실수 등 외적인 요인에 의해 발생하는 계열</li>
<li>checked exception</li>
<li>대처코드가 없으면 컴파일 진행</li>
</ul>
</li>
</ul>
<h2 id="예외-처리-키워드">예외 처리 키워드</h2>
<ol>
<li>직접 처리 <ul>
<li>try {} : 예외가 발생할 가능성이 있는 코드를 포함하는 블록</li>
<li>catch (예외매개변수) {} : 예외가 발생했을 때 실행 할 코드 블록</li>
<li>finally {} : 예외 발생 여부와 상관없이 항상 실행되는 코드 블록</li>
</ul>
</li>
<li>간접 처리 (처리 위임)<ul>
<li>throws : 메서드 선언부에 사용되며, 메서드에서 발생 가능한 예외를 호출자에게 전달</li>
</ul>
</li>
<li>예외를 직접 발생시킬 때<ul>
<li>throw : 예외를 명시적으로 발생시키는 키워드</li>
</ul>
</li>
</ol>
<h2 id="예외처리-trycatch-구문">예외처리 (try~catch 구문)</h2>
<ul>
<li>프로그램 실행 시 발생할 수 있는 예외에 대한 대비 코드 작성</li>
<li>프로그램의 비정상적인 종료를 막고, 정상적인 상태를 유지할 수 있도록함</li>
<li>중괄호(블록) 생략 불가능</li>
<li>중첩 된 예외처리 : 블록 안에 또 다른 try ~ catch 구문이 올 수 있음</li>
</ul>
<pre><code class="language-java">package com.ssafy.try_catch;

public class TryCatchTest01 {
    public static void main(String[] args) {
        int[] nums = {10}; // 선언과 동시에 초기화할 때만 가능한 문법

        try {
            System.out.println(&quot;정상 코드 1&quot;);
            System.out.println(nums[10]); //예외가 발생할 수 있는 코드
            System.out.println(&quot;정상 코드 2&quot;);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(&quot;예외 발생 처리 코드&quot;);
        }
        System.out.println(&quot;프로그램 끝&quot;);
    }
}
</code></pre>
<pre><code class="language-java">정상 코드 1
예외 발생 처리 코드
프로그램 끝</code></pre>
<p><img alt="" src="https://velog.velcdn.com/images/danhye821/post/6230b0e7-1bdd-4573-ba00-73166fd5f989/image.png" /></p>
<h2 id="다중-예외처리">다중 예외처리</h2>
<ul>
<li>try 블록에서 여러 종류의 예외가 발생할 경우</li>
<li>하나의 try 블록에 여러 개의 catch블록 추가 가능</li>
</ul>
<pre><code class="language-java">package com.ssafy.try_catch;

//다중 처리
public class TryCatchTest02 {
    public static void main(String[] args) {
        int[] nums = {10}; // 선언과 동시에 초기화할 때만 가능한 문법

        try {
            System.out.println(&quot;정상 코드 1&quot;);
            //코드는 엄청나게 많이 쓸거야 !!
            System.out.println(10 / 0); //예외가 발생할 수 있는 코드
            System.out.println(&quot;정상 코드 2&quot;);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println(&quot;인덱스 예외 처리 구문&quot;);
        }catch (ArithmeticException e) {
            System.out.println(&quot;수학적 이슈 예외처리 구문&quot;);
        }
        System.out.println(&quot;프로그램 끝&quot;);
    }
}
</code></pre>
<pre><code class="language-java">정상 코드 1
수학적 이슈 예외처리 구문
프로그램 끝
</code></pre>
<h3 id="다중-예외처리-유의-사항">다중 예외처리 유의 사항</h3>
<ul>
<li>예외 객체에 해당하는 catch 문장을 찾을 때는 다형성이 적용됨</li>
<li>상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 (상속 관계 무관)</li>
<li>순서가 중요하지는 않아</li>
<li>상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음</li>
<li>상속 관계에서 작은 범위 (조상) 순으로 정의</li>
</ul>
<h2 id="exception-인스턴스의-주요-메서드">Exception 인스턴스의 주요 메서드</h2>
<ul>
<li>getMessage() : 발생된 예외에 대한 구체적인 메세지를 반환</li>
<li>printStackTrace() : 예외 발생 당시의 호출 스택(Call Stack)을 출력</li>
</ul>
<h3 id="finally">finally</h3>
<ul>
<li>finally는 예외 발생 여부와 상관 없이 언제나 실행</li>
<li>예외 발생 시 → try - catch - finally 순으로 코드 실행</li>
<li>예외 미발생시 → try - finally 순으로 코드 실행</li>
<li>중간에 return이 있어도 finally 블록 수행 후 반환</li>
</ul>
<pre><code class="language-java">package com.ssafy.try_catch;

//다중 처리
public class TryCatchTest03 {
    public static void main(String[] args) {
        int[] nums = {10}; // 선언과 동시에 초기화할 때만 가능한 문법

        try{
            System.out.println(&quot;1&quot;);
            System.out.println(nums[10]);
            System.out.println(&quot;2&quot;);
            return;
        }catch(ArrayIndexOutOfBoundsException e) {
            System.out.println(&quot;3&quot;);
            return;
        }finally {
            //중간에 return 이 존재하더라도 얘는 실행 한다..!
            System.out.println(&quot;4&quot;);
        }

//        System.out.println(&quot;5&quot;);
    }
}
</code></pre>
<pre><code class="language-java">1
3
4</code></pre>
<h3 id="자동-자원-반납-구문-try-with-resources">자동 자원 반납 구문 (try with resources)</h3>
<ul>
<li>자원 등을 반납할 때 finally에서 close()를 통해 반납을 주로 함</li>
<li>코드가 지저분해지고 다른 예외 상황을 발생 시킬 수 있음</li>
<li>try() → 괄호 안에 객체를 생성하는 코드를 작성하면, 해당 객체는 close()를 호출하지 않아도 블록을 벗어 나는 순간 close() 가 호출 됨</li>
<li>해당 객체의 클래스가 AutoCloseable 이라는 인터페이스를 구현해야 함</li>
</ul>
<h1 id="throws-활용">throws 활용</h1>
<h3 id="메서드에서-예외-던지기">메서드에서 예외 던지기</h3>
<ul>
<li>메서드 선언 부에 throws 키워드를 사용하여 예외 작성</li>
<li>예외가 여러 개일 경우, , (Comma)를 이용하여 나열</li>
<li>메서드가 예외를 처리하는 것이 아닌 전달</li>
<li>조상 타입의 예외로 처리 가능</li>
</ul>
<h3 id="메서드-재정의와-throws">메서드 재정의와 throws</h3>
<ul>
<li>메서드 재정의 시 조상클래스 메서드가 던지는 예외보다 부모 예외를 던질 수 없음</li>
</ul>
<pre><code class="language-java">package com.ssafy.throwstest;

import java.io.FileNotFoundException;
import java.io.IOException;

class Parent{
    void method1() throws IOException {

    }
    void method2() throws ClassNotFoundException {

    }
}

class Child extends Parent {
    @Override
    void method1() throws FileNotFoundException {
    }
//    @Override
//    void method2() throws Exception { 
        //자식은 부모보다 더 큰 예외를 걸 수 없다.
//    }
}

public class ThrowsTest02 {
    public static void main(String[] args){
        Child c= new Child();
//        c.method1();
    }
}
</code></pre>
<h1 id="사용자-정의-예외-처리">사용자 정의 예외 처리</h1>
<h2 id="사용자-정의-예외">사용자 정의 예외</h2>
<ul>
<li>기존에 정의 된 예외 이외에 사용자가 직접 정의 예외를 작성할 수 있음</li>
<li>대부분 Exception 또는 RuntimeException 클래스를 상속받아 작성<ul>
<li>checked exception 활용 : 명시적 예외 처리 또는 throws 필요 (코드는 복잡해지만 처리, 누락 등 오류 발생 가능성은 down)</li>
<li>runtime exception 활용 : 묵시적 예외 처리 가능 (코드가 간결해지지만 예외 처리, 누락 가능성 발생)</li>
</ul>
</li>
</ul>